baseURL = "https://photos.ntnguyen.com"

[author]
    name = "Nguyễn Thành Nguyên"

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    timeout = "10m"
    [params.gallerydeluxe]
        shuffle     = true
        reverse     = true
        enable_exif = false

[module]
    [module.hugoVersion]
        min = "0.108.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "i18n"
        target = "i18n"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe"
    [[module.imports]]
        path = "github.com/bep/hugo-mod-misc/common-partials"
