[build]
    publish = "content/public"
    command = "./hugo-ci.sh --gc -s content --minify"

    [build.environment]
        HUGO_VERSION = "0.115.1"

[context.deploy-preview]
    command = "./hugo-ci.sh -s content --minify -D -F -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
        HUGO_VERSION = "0.115.1"

[context.branch-deploy]
    command = "./hugo-ci.sh -s content --minify --gc -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
        HUGO_VERSION = "0.115.1"
